name: CI

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: current
            purescript: "0.15.15"
            package-set: "80.9.0"
          - name: 0.10-compatible
            purescript: "0.15.12"
            package-set: "46.0.2"
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - uses: purescript-contrib/setup-purescript@main
        with:
          purescript: ${{ matrix.purescript }}
          spago: "1.0.4"

      - run: spago upgrade --package-set ${{ matrix.package-set }}

      - run: spago build --pedantic-packages

      - run: spago test --pedantic-packages
